site_name: Investiment Funds Manager - Technical Documentation

theme:
  name: mkdocs
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - python

markdown_extensions:
  - toc:
      permalink: "#"

nav:
  - Home: index.md
  - Clients: clients.md
  - Funds: funds.md